-- MySQL Script generated by MySQL Workbench
-- Mon Jun 10 11:41:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categorie` (
  `id_categorie` INT NOT NULL,
  `nom_categorie` VARCHAR(64) NOT NULL,
  `description_categorie` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_categorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article` (
  `id_article` INT NOT NULL,
  `nom_article` VARCHAR(64) NOT NULL,
  `description_article` VARCHAR(255) NOT NULL,
  `prix_article` DECIMAL(6,2) NOT NULL,
  `id_categorie` INT NOT NULL,
  PRIMARY KEY (`id_article`),
  INDEX `fk_article_Categorie1_idx` (`id_categorie` ASC),
  CONSTRAINT `fk_article_Categorie1`
    FOREIGN KEY (`id_categorie`)
    REFERENCES `mydb`.`Categorie` (`id_categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commande` (
  `id_commande` INT NOT NULL,
  `numero_commande` INT NOT NULL,
  `date_achat_commande` DATETIME NOT NULL,
  `desciption_commande` VARCHAR(255) NOT NULL,
  `statut_commande` VARCHAR(45) NOT NULL,
  `id_article` INT NOT NULL,
  PRIMARY KEY (`id_commande`),
  UNIQUE INDEX `numero_commande_UNIQUE` (`numero_commande` ASC),
  INDEX `fk_commande_article1_idx` (`id_article` ASC),
  CONSTRAINT `fk_commande_article1`
    FOREIGN KEY (`id_article`)
    REFERENCES `mydb`.`article` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id_client` INT NOT NULL,
  `prenom_client` VARCHAR(64) NOT NULL,
  `nom_client` VARCHAR(64) NOT NULL,
  `adresse_client` VARCHAR(128) NOT NULL,
  `adresse_compl_client` VARCHAR(128) NULL,
  `cp_client` INT NOT NULL,
  `ville_client` VARCHAR(64) NOT NULL,
  `email_client` VARCHAR(64) NOT NULL,
  `mdp_client` VARCHAR(20) NOT NULL,
  `id_commande` INT NOT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `email_client_UNIQUE` (`email_client` ASC),
  INDEX `fk_client_commande_idx` (`id_commande` ASC),
  CONSTRAINT `fk_client_commande`
    FOREIGN KEY (`id_commande`)
    REFERENCES `mydb`.`commande` (`id_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
